spring.application.name=medassistant

# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/medassistant?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=meduser
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Twilio Config
twilio.accountSid=
twilio.authToken=
twilio.phoneNumber=
caregiver.pin=03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4